### ISSUE TITLE
Consider adding version to incorporate locking 

### ISSUE THREAD

**Issue by amit5881** [nitsshukla/AgodaBooking#2]
https://github.com/nitsshukla/AgodaBooking/blob/24095baf0c394ba4ae17d8e56d237e8eaaa461ff/src/main/java/com/agoda/booking/tracker/dtos/BookingRequest.java#L23

**Comment by nitsshukla-zz** [comment]
But IMO we aren't doing any sort of transaction here, it's a simple one way POST request.
